whyrusleeping/cbor-gen

gen.go, testing/cbor_gen.go, testing/cbor_map_gen.go, testing/types.go
=> Support uint64 pointers

testgen/main.go, testing/cbor_gen.go, testing/roundtrip_test.go, testing/types.go, utils.go
Handle two unusual cases for a cbg.Deferred value in the Marshalling process
- Case: a *cbg.Deferred value is marshaled when the pointer is nil
Resolution: add a self nil check in the Marshall method for *cbg.Deferred and write a cbor.Null
- Case: a *cbg.Deferred value is not nil but has a Raw field that is nil
Resolution: this shouldn't happen. It means you forgot to serialize the deferred value into Raw. Moreover, currently it produces unpredictable behavior because Marshall will succeed (writing nothing), but then nothing is written to the buffer so if a Deferred is in a struct, the immediate proceeding field will likely have an unpredictable error, as it's data will be read into Raw on Unmarshal. Instead, return error on Marshal for this case.
=> Handle Nil values for cbg.Deferred

utils.go, utils_test.go
Closes https://github.com/whyrusleeping/cbor-gen/issues/23.
=> deferred: restrict max length

gen.go, testing/cbor_gen.go, testing/cbor_map_gen.go
fixes #21
We could also make sure every field write writes to the field, no matter what. However, this is much safer.
=> fix: clear struct state on unmarshal

gen.go, peeker.go, peeker_test.go, testing/bench_test.go, testing/cbor_gen.go, testing/cbor_map_gen.go, utils.go, utils_test.go
This optimizes:
1. readByte: It turns out that frequently casting an interface to an interface is really slow, but casting an interface to a concrete type is fast. 
2. Deferred: This avoids most of the unnecessary allocations and copies in `Deferred.UnmarshalCBOR`, and switches to an iterative (rather than recursive) implementation.
3. ScanForLinks: As with Deferred, this is now non-recursive.
Note: depth limits have been removed from Deferred as the implementation is no longer recursive. ScanForLinks never appeared to have depth limits.
=> Optimize decoding

gen.go, peeker.go, peeker_test.go, testing/cbor_gen.go, testing/cbor_map_gen.go, utils.go
Buffering could lead to reading over the end of the object, corrupting the next object. We weren't running into this in practice because we're using `bytes.Buffer` everywhere (so we were never hitting the `bufio` code path, as far as I can tell).
This patch also gets rid of "PeekByte" and uses the standard ReadByte/UnreadByte interfaces. That way, we can avoid wrapping the byte reader in the happy path, saving some overhead.
Note: this is an API (but not format) breaking change. Generated files will have to be re-generated.
=> Switch to non-buffering byte reader

utils.go
When using cbor-gen, we _usually_ work with byte buffers/readers. Calling `ReadByte` on a byte.Reader/byte.Buffer is much faster than calling `Read` and copying into a slice.
name            old time/op    new time/op    delta
Marshaling-4       911ns ± 2%     904ns ± 5%     ~     (p=0.646 n=9+10)
Unmarshaling-4    4.46µs ± 1%    3.94µs ± 2%  -11.55%  (p=0.000 n=10+8)
LinkScan-4        4.65µs ± 2%    4.01µs ± 2%  -13.76%  (p=0.000 n=9+10)
Deferred-4        3.68µs ± 3%    3.02µs ± 4%  -17.91%  (p=0.000 n=10+10)
name            old alloc/op   new alloc/op   delta
Marshaling-4        160B ± 0%      160B ± 0%     ~     (all equal)
Unmarshaling-4    3.46kB ± 0%    3.46kB ± 0%     ~     (all equal)
LinkScan-4          880B ± 0%      880B ± 0%     ~     (p=0.650 n=10+10)
Deferred-4         96.0B …
=> optimize byte reading

gen.go, testgen/main.go, testing/cbor_map_gen.go, testing/roundtrip_test.go, testing/types.go
We use it for writing the keys.
=> Always allocate scratch space when marshalling into a map.

utils.go
This gives a pretty significant speedup and drops us down to an allocation per
link.
name        old time/op    new time/op    delta
LinkScan-4    4.03µs ± 3%    1.26µs ±12%  -68.79%  (p=0.000 n=10+10)
name        old alloc/op   new alloc/op   delta
LinkScan-4      881B ± 0%      112B ± 0%  -87.29%  (p=0.002 n=8+10)
name        old allocs/op  new allocs/op  delta
LinkScan-4      25.0 ± 0%       1.0 ± 0%  -96.00%  (p=0.000 n=10+10)
=> Optimize discarding in ScanForLinks

validate.go, validate_test.go
This function is equivalent to Deferred.UnmarshalCBOR, just more efficient because it doesn't copy.
=> Add a validate function.

gen.go, package.go, testgen/main.go, testing/cbor_gen.go, testing/cbor_map_gen.go, testing/roundtrip_test.go, testing/types.go
It's useful to be able to add a field to a struct and for older versions of the code to ignore the added field when unmarshaling.
```
// V1
type Animal struct {
Legs int
}
...
// V2
type Animal struct {
Legs int
Eyes int
}
```
This PR modifies the unmarshaling code such that it will ignore any fields it doesn't recognize.
=> feat: allow unmarshaling of struct with more fields than marshaled struct

writefile.go
=> doc: document Write*EncodersToFile functions

gen.go, testing/cbor_gen.go, testing/cbor_map_gen.go
This fix the following bug:
Currently generated code for unmarshalling `uint8` field:
```go
// t.Type (service.TimeFilterType) (uint8)
maj, extra, err = cbg.CborReadHeaderBuf(br, scratch)
if err != nil {
return err
}
if maj != cbg.MajUnsignedInt {
return fmt.Errorf("wrong type for uint8 field")
}
if extra > math.MaxUint8 {
return fmt.Errorf("integer in input was too large for uint8 field")
}
t.Type = TimeFilterType(extra)
```
`math` package is used in above code but the import statement for `math` is not generated, so generated code won't compile.
@Stebalien
=> fix: import "math" in generated code for uint8 unmarshalling

cbor_cid.go, utils.go
This just makes our lives easier when using them. We can now, e.g., pass `CborInt(1)` to something that expects a `CBORMarshaler`.
=> feat: take cbor adapters by-value when encoding

utils.go, utils_test.go
readByteBuf was incorrectly returning the error (EOF) before returning the first byte read. It is a valid for an io.Reader to return both n == 1 and err == EOF (see https://pkg.go.dev/io#Reader). But readByteBuf dropped the read byte and instead returned EOF.
This uses io.ReadFull to handle this logic, where io.ReadFull follows these semantics:
> ReadFull reads exactly len(buf) bytes from r into buf. It returns the number of bytes copied and an error if fewer bytes were read. The error is EOF only if no bytes were read. If an EOF happens after reading some but not all the bytes, ReadFull returns ErrUnexpectedEOF. On return, n == len(buf) if and only if err == nil. If r returns an error having read at least len(buf) bytes, the error is dropped.
This also makes sure that the `discard` …
=> Fix read bug in readByteBuf

peeker.go, utils_test.go
A continuation of #60. There was an edge case that wasn't checked. If the reader was a peeker it would simply call peeker.ReadByte, which didn't follow the semantics of buffer.ReadByte, readByteBuf, or any other ReadByte method in the Go library. Specifically it should only return an error if it failed to read a byte.
I added a test and also tested this branch against my end code to verify it actually fixes the issue.
@Stebalien since they already have context from #60.
=> Make peeker.ReadByte follow buffer.ReadByte semantics

gen.go, io.go, testing/bench_test.go, testing/cbor_gen.go, testing/cbor_map_gen.go, utils.go, validate.go
Gives a better tradeoff between cpu and allocations than #65 so I am closing that PR in favour of this one.
Adds CborReader and CborWriter that contain a small buffer for optimizing CBOR header reads and writes. In contrast to #65 no pool is used for header buffers, instead the reader or writer reuses a single buffer over multiple operations. A package level pool is used for 8k buffers used when reading strings. The benchmarks show an increase in cpu but allocations are substantially reduced.
Benchstat comparison with master:
```
name               old time/op    new time/op    delta
Marshaling-8          564ns ± 1%     840ns ± 0%  +49.06%  (p=0.000 n=9+9)
Unmarshaling-8       2.75µs ± 5%    3.07µs ± 9%  +11.71%  (p=0.000 n=10+10)
LinkScan-8            744ns ± 0%     932ns ± 1%  +25.26% …
```
=> Add CborReader and CborWriter

utils.go, utils_test.go
We can already _decode_ a raw byte array, but there wasn't a way to encode one.
=> feat: add the ability to encode a byte array

gen.go, io.go, testing/cbor_gen.go, testing/cbor_map_gen.go, utils.go
The interface type assertion of `io.WriteString` was showing up pretty noticeably in some of my benchmarks, this makes that go away (almost) entirely. The benchmark in question went from around 3600ns/op to 3100ns/op.
=> optimize anything using WriteString

gen.go, go.sum, testgen/main.go, testing/cbor_map_gen.go, testing/roundtrip_test.go, testing/types.go
Adds test cases and support for map with value type `string`.
=> Support gen for map with value type `string`

deferred.go, helper_types.go, links.go, utils.go
while i was working on #88 i was bothered by how messy util.go was getting, so i split it up a bit.
=> some cleanup for easier reading

gen.go, testing/cbor_gen.go, testing/cbor_map_gen.go
Sometimes you just want to set these globally
=> turn max length consts into global vars

gen.go, testgen/main.go, testing/cbor_gen.go, testing/roundtrip_test.go, testing/types.go
This PR adds support for 'transparent' encoding, either in structs with `cborgen:"transparent"` tag (which can be used with other tags), or by just defining a newtype that isn't a struct
```go
type IntAlias int64
type IntArray struct {
Ints []int64 `cborgen:"transparent"`
}
type IntAliasArray struct {
Ints []IntAlias `cborgen:"transparent"`
}
type IntArrayNewType []int64
type IntArrayAliasNewType []IntAlias
type MapTransparentType map[string]string
```
Opinions this is based on:
* Transparent encoders can only be generated in tuple mode
*  Map mode entries have name prefixes, so technically tuple mode makes more sense
* Only one transparent entry in structs with transparent entries
* Technically we could allow multiple entries, in any case we're just stripping the array header, but that …
=> Transparent encoding

deferred.go
`bytes.Buffer` will always overallocate (for performance) and we don't have a great way of predicting the correct size. So, instead, copy once when we're done.
We we're seeing 10x the memory usage expected in a network migration in Filecoin.
=> fix: reduce memory held by deferred objects

links.go, testing/bench_test.go
`ioutil` is deprecated as of Go 1.16, this value is simply [io.Discard](https://pkg.go.dev/io#Discard).
> https://pkg.go.dev/io/ioutil
=> Change ioutil to io

gen.go, testgen/main.go, testing/cbor_gen.go, testing/roundtrip_test.go, testing/types.go
We don't encode the sign, so we should reject these numbers.
=> fix: reject negative big integers

gen.go, utils.go, utils_test.go, writefile.go
also, allow *Foo{} demo object inputs
=> optionally sort type names in generated code file

gen.go, io.go, peeker.go, testgen/main.go, testing/cbor_map_gen.go, testing/roundtrip_test.go, testing/types.go, utils.go
reuse buffers more and use optimized read paths when available. 
Before:
```
why@sirius ~/c/cbor-gen (master)> go test ./testing -run XXX -bench=.
goos: linux
goarch: amd64
pkg: github.com/whyrusleeping/cbor-gen/testing
cpu: AMD Ryzen Threadripper 3970X 32-Core Processor
BenchmarkMarshaling-64         	 1856397	       712.1 ns/op	      48 B/op	       1 allocs/op
BenchmarkUnmarshaling-64       	  199536	      6274 ns/op	    1777 B/op	      21 allocs/op
BenchmarkLinkScan-64           	  729843	      1645 ns/op	     112 B/op	       1 allocs/op
BenchmarkDeferred-64           	  505626	      2223 ns/op	      40 B/op	       2 allocs/op
BenchmarkMapMarshaling-64      	 2326390	       497.8 ns/op	      50 B/op	       3 allocs/op
BenchmarkMapUnmarshaling-64    	  140995	      8113 ns/op	    2043 …
```
=> improve allocations in map serialization

testing/cbor_map_gen.go
Fix inconsistent checked-in code with output of `make gentest`.
=> Regenerate test files

gen.go, testgen/main.go, testing/cbor_gen.go, testing/optional_test.go, testing/types.go
Motivation: This makes it possible to add fields to structs while still being able to decode versions that don't include those fields.
Fields at the end of a tuple-encoded struct can be now marked as `cborgen:"optional"`. When thus marked:
1. These fields are not required when unmarshaling CBOR into this struct. Instead, they'll be initialized to their respective zero values.
2. These fields are still written out when marshaling into CBOR.
Marking map-encoded struct fields as optional is legal but has no impact in practice as all map fields are optional. As before, tuple-encoded structs will not omit "omitempty" fields, even when optional.
=> feat: add support for optional fields at the end of tuple structs

gen.go, testing/cbor_gen.go, testing/optional_test.go, testing/types.go
A bug in https://github.com/whyrusleeping/cbor-gen/pull/109; many of the unmarshal components just reuse the primary `maj, extra, err` variables for `cr.ReadHeader()`, so that when you get to the end and want to use `extra` to length-check, it's already been overwritten with something else. This doesn't show up in the current tests because `int64` happens to block scope and create new variables. But uint64 doesn't, so that's included in the test now and it fails without the fix. I remember hitting this when I was doing the generics work too.
This is the easy and less painful way of fixing it. Just capture the length and we're done.
https://github.com/whyrusleeping/cbor-gen/pull/111 is the "hard way" (proper way).
We can debate and pick one.
=> fix: capture field count early for "optional" length check
